# Generated by Django 5.1 on 2024-08-21 22:23

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='icon',
            field=models.ImageField(default='static/product_photo/default_icon.png', upload_to=shop.models.icon_name),
        ),
    ]
