# Generated by Django 5.1 on 2024-08-21 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Introduction',
            new_name='introduction',
        ),
    ]
