# Generated by Django 5.1 on 2024-08-22 00:53

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_introduction_product_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='icon',
            field=models.ImageField(default='product_photo/default_icon.png', upload_to=shop.models.icon_name),
        ),
    ]
