# Generated by Django 5.1 on 2024-08-19 16:45

import activity.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField()),
                ('stop_date', models.DateTimeField()),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to=activity.models.title_photo)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=activity.models.photo_name)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='activity.activity')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
        ),
    ]
