# Generated by Django 5.1 on 2024-08-13 19:32

import member.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=50, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=member.models.icon_name)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('tel', models.CharField(blank=True, max_length=12, null=True)),
                ('role', models.CharField(choices=[('owner', '烟花'), ('ADMIN', '小幫手'), ('member', '小羊')], default='member', max_length=10)),
            ],
        ),
    ]
