# Generated by Django 5.1 on 2024-08-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_rename_user_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='verification',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(error_messages={'unique': '有人用摟'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(error_messages={'unique': '已有重複帳號...禁止冒名頂替'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(blank=True, choices=[('owner', '烟花'), ('ADMIN', '小幫手'), ('member', '小羊')], default='member', max_length=10),
        ),
    ]
