# Generated by Django 5.1 on 2024-08-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_item_price_alter_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='addressee',
            field=models.TextField(default='', max_length=6),
            preserve_default=False,
        ),
    ]
