# Generated by Django 5.1 on 2024-08-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_addressee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(blank=True, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
