# Generated by Django 5.1 on 2024-09-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('等待確認', 'Pending'), ('等待出貨', 'Processed'), ('已出貨', 'Shipped'), ('已交付', 'Delivered'), ('取消', 'Canceled')], default='等待確認', max_length=15),
        ),
    ]
